config/routes.rb
JeromeResume::Application.routes.draw do
  
  
  
  
  resources :posts
  get '/projects', to: 'posts#projects', as: :projects
  get '/skills', to: 'posts#skills', as: :skills
  get '/recommendations', to: 'posts#recommendations', as: :recs  
    
  root :to => 'posts#home'

  
  
  


end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def home
    
  end
  
  def projects
    
  end
  
  def skills
    
  end
  
  def recommendations
    
  end
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jerome Manuel" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to (image_tag("jeromemanuel_LinkedIn_icon.svg")), "http://www.linkedin.com/in/jeromemanuel"  %></li>
              <li><%= link_to (image_tag("jeromemanuel_Twitter_icon.svg")), "https://twitter.com/jeromemanuel"  %></li>
              <li><%= link_to (image_tag("jeromemanuel_contact_icon.svg")),   %> </li>
							<li><%= link_to (image_tag("home-icon.svg", :class => "home-icon")), root_url%><div class="pull-left">jtmanuel@gmail.com</div></li>
							<!-- <div class="pull-right">
															me@jeromemanuel.com
														</div> -->
            </ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
				<div class="container">
					<div class="pull-right">
        		&copy; Jerome Manuel 2013
					</div>
				</div>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-41757053-1', 'jeromemanuel.com');
		  ga('send', 'pageview');

		</script>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<div class="row">
	<div class="span2 offset10">
			<!-- me@jeromemanuel.com -->
	</div>
	<div class="span12">
		
		<%= image_tag('jerome.png', :class => 'image pull-right')%>
	</div>
</div>

<div class="row">
	<div class="span12">
		<div class="home-quote-content">I am who I am. I live with <span class="home-quote-content-focus">hope</span>, <span class="home-quote-content-focus">desire</span>, <span class="home-quote-content-focus">passion</span>, and <span class="home-quote-content-focus">determination</span>:</div></br>
		<div class="home-quote-content">to <span class="home-quote-content-focus">make a difference</span>,</br> to <span class="home-quote-content-focus">change the world</span>,</br> to <span class="home-quote-content-focus">do something remarkable</span>,</br> and to <span class="home-quote-content-focus">bring happiness to others</span>.</br></br> </div>
			<div class="home-quote-content">I live to <span class="home-quote-content-focus">create</span>, to <span class="home-quote-content-focus">build</span>, to <span class="home-quote-content-focus">innovate</span>, and to <span class="home-quote-content-focus">inspire</span>.</div></br>
		</div>
	</div>
</div>

<div class="content-separator"></div>

<!-- <div class="row"> -->
	<div class="project-container center-icons">
		<%= image_tag('projects_icon.svg', :class => 'category-icon')%>
		<div class="category-separator"></div>
		<%= link_to (image_tag('VIVE-LOGO.png', :class => 'project-logos')), 'http://www.viveproject.co'%>
		<!-- <div class="category-separator"></div> -->
		<%= link_to (image_tag('that1spot-logo.png', :class => 'project-logos')), 'http://that1spot.com'%>
	</div>
	
	<div class="project-container center-icons">
		<%= link_to (image_tag('skills-icon.svg', :class => 'category-icon')), skills_url %></br></br>
		<%= link_to 'See more >>', skills_url %>
		<div class="category-separator"></div>
		<%= link_to (image_tag('rails.png', :class => 'skill-logos')), skills_url%>
		<%= link_to (image_tag('seo-icon.svg', :class => 'skill-logos')), skills_url%>
		<%= link_to (image_tag('Google-Analytics-icon.png', :class => 'skill-logos')), skills_url%>
		<%= link_to (image_tag('social-media-icon.svg', :class => 'skill-logos')), skills_url%>
	 	<%= link_to (image_tag('Freddie_OG.png', :class => 'skill-logos')), skills_url%>
		<%= link_to (image_tag('illustrator_cs5_mnemonic_no_shadow_png.png', :class => 'skill-logos')), skills_url%>
		<%= link_to (image_tag('Adobe_Photoshop_CS5_icon.png', :class => 'skill-logos')), skills_url%></br>
		<div class="category-text">
			<%= link_to "& more ...", skills_url%>
		</div>
	</div>
	
	<div class="project-container center-icons">
		<%= link_to (image_tag('recs-icon.svg', :class => 'category-icon')), recs_url %></br></br>
		via LinkedIn 
		<%= link_to 'See more >>', recs_url %>
		<div class="category-separator"></div>
		<%= link_to (image_tag('kent-rec.png', :class => 'rec-image')), recs_url %>
		<%= link_to (image_tag('john-rec.png', :class => 'rec-image')), recs_url %>
		<%= link_to (image_tag('sophie-rec.png', :class => 'rec-image')), recs_url %></br></br>
		<div class="category-text">
			<%= link_to "+ 2 >>", recs_url %>
		</div>
	</div>
<!-- </div> -->


<div class="content-separator"></div>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/projects.html.erb
<%= image_tag('projects_icon.svg', :class => 'category-icon')%>

<%= link_to (image_tag('VIVE-LOGO.png', :class => 'project-logos')), 'http://www.viveproject.co'%>

<%= link_to (image_tag('that1spot-logo.png', :class => 'project-logos')), 'http://that1spot.com'%>



<div class="content-separator"></div>

app/views/posts/recommendations.html.erb
<%= image_tag('recs-icon.svg', :class => 'category-icon')%>
<%= link_to (image_tag('kent-rec.png', :class => 'pull-right rec-image')), 'http://www.linkedin.com/in/jeromemanuel' %>
<%= link_to (image_tag('john-rec.png', :class => 'pull-right rec-image')), 'http://www.linkedin.com/in/jeromemanuel' %>
<%= link_to (image_tag('sophie-rec.png', :class => 'pull-right rec-image')), 'http://www.linkedin.com/in/jeromemanuel' %>
<%= link_to (image_tag('sarah-rec.png', :class => 'pull-right rec-image')), 'http://www.linkedin.com/in/jeromemanuel' %>
<%= link_to (image_tag('linkedin-rec1.png', :class => 'pull-right rec-image')), 'http://www.linkedin.com/in/jeromemanuel' %>


<div class="content-separator"></div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/skills.html.erb
<%= image_tag('skills-icon.svg', :class => 'category-icon')%>	

<ul class="pull-right">
	<li class="skills-text">Email Marketing, Market Research & Surveying with Mailchimp, and SurveyMonkey</li>
	<li class="skills-text">SEO - keyword analysis, keyword usage and targeting, on-page SEO, and link building</li>
	<li class="skills-text">Social media marketing - Twitter, Facebook, Google+, Pinterest, Tumblr, Instagram, etc.</li>
	<li class="skills-text">Product Launch Management, Product Development, User Interface, and User Experience</li>
	<li class="skills-text">Online Analysis: Google Analytics, Addthis Analytics, SEOmoz Analytics</li>
	<li class="skills-text">Budget Management, ROI Analysis, Competitve Analysis</li>
	<li class="skills-text">Adobe Creative Suite: Photoshop, and Illustrator, etc.</li>
	<li class="skills-text">Microsoft Office Suite: Word, Excel, Access, and PowerPoint, etc.</li>
	<li class="skills-text">System Administrator on SalesForce.com CRM, Hyperion</li>
	<li class="skills-text">Ruby, Ruby on Rails, HTML5, CSS, Javascript, jQuery, Twitter Bootstrap</li>
</ul>


<div class="content-separator"></div>